gojue/ecapture

Makefile, kern/bash_kern.c, kern/gnutls_kern.c, kern/mysqld56_kern.c, kern/nspr_kern.c
access registers with PT_REGS macros and add LINUX_ARCH flags to makefile.
=> access registers with PT_REGS macros & add LINUX_ARCH flags

user/config_openssl.go
via: #29 ubuntu21.10 error :connect symbol cant found
wipe symbol connect search path. range a strings array who defined match all linux version.
=> user: fix #29 ubuntu21.10 error :connect symbol cant found

Makefile, Makefile.nocore, kern/bash_kern.c, kern/common.h, kern/core_type.h, kern/gnutls_kern.c, kern/mysqld_kern.c, kern/nspr_kern.c, kern/openssl_kern.c, main.go
fix  #31 
1. add Makefile.nocore
2. support no co-re with linux headers by KERN_SRC_PATH.
=> support no co-re version on linux kernel >= 5.2 

Makefile, cli/cmd/tls.go, kern/README.md, kern/bash_kern.c, kern/common.h, kern/gnutls_kern.c, kern/mysqld_kern.c, kern/nspr_kern.c, kern/openssl_kern.c, user/config_nspr.go, user/event_nspr.go, user/iconfig.go, user/probe_bash.go, user/probe_gnutls.go, user/probe_nspr.go, user/probe_openssl.go
1,global variable declaration will compile to .rodata/.bss section in ELF file.
2, haveMapMutabilityModifiers variable will create `ARRAY` type ebpf map with `BPF_F_RDONLY_PROG` flag to detect system supported in syscalls.go .
3. so need to remove global variable on kernel version less than 5.2 via haveMapMutabilityModifiers in cilium/ebpf/syscalls.go
4. more info https://github.com/cilium/ebpf/commit/f5942f5215490ef5f1bc2072f2c925ce7712a20e
=> * : Fix #39 .rodata: map create: read- and write-only maps not supported (requires >= v5.2)

Makefile, README.md, README_CN.md, cli/cmd/root.go
*: update clang version to 9 from 12.
=> set clang version lower to 9 from 12

Makefile, kern/bash_kern.c, kern/common.h, kern/ecapture.h, kern/gnutls_kern.c, kern/mysqld_kern.c, kern/nspr_kern.c, kern/openssl_kern.c, user/event_mysqld.go, user/probe_mysqld.go
=> ADD mysqld dispatch_command return value.

kern/bash_kern.c, user/event_bash.go, user/probe_bash.go
the commond which been exec successfully will return 0,otherwhise will return errcode.
=> added return value of bash module.

kern/bash_kern.c, kern/common.h, user/event_bash.go
**bash监控中遇到诸如:wget、curl场景时，默认命令长度80相对较短**
如下述命令
`wget https://support.asiainfo-sec.com/TM-Product/Product/Deep_Security/DS_for_Multi_Hypervisor/10.5_MH/DSA/Agent-RedHat_EL7-10.5.0-3336.x86_64.zip`
因此针对一般情况，修改line长度到256字节
**存在问题**
修改到256依旧无法满足超长命令情况（如更长的url), 不过一般情况下应该可以满足需求
=> change bash line size to 256 bytes

user/event_bash.go, user/event_gnutls.go, user/event_mysqld.go, user/event_nspr.go, user/event_openssl.go, user/event_postgres.go, user/ievent.go, user/imodule.go, user/probe_bash.go, user/probe_gnutls.go, user/probe_mysqld.go, user/probe_nspr.go, user/probe_openssl.go, user/probe_postgres.go
=> code refactoring: event dispatcher 

README.md, README_CN.md
add readme info for how to use other libs, such as: libressl/boringssl
=> add notes for how to use ecapture in other libs

kern/openssl_kern.c, kern/postgres_kern.c, user/event_openssl.go
add tls/ssl version info. only for openssl.
fixed: #61
code format
=> * : add TLS/SSL Version info (openssl).

cli/cmd/global.go, cli/cmd/root.go, cli/cmd/tls.go, user/common.go, user/config_gnutls.go, user/config_nspr.go, user/config_openssl.go, user/iconfig.go
When run ecapture in Kubernetes pod, ecapture is given
--libssl, --pthread to specific lib location, but ecapture
continues to auto search gnutls lib and result in error
2022/06/05 16:46:48 pid info :3305486
2022/06/05 16:46:48 start to run EBPFProbeOPENSSL module
2022/06/05 16:46:48 start to run EBPFProbeGNUTLS module <====
2022/06/05 16:46:48 lstat /etc/ld.so.conf: no such file or directory <===
2022/06/05 16:46:48 invalid argument <====
see https://github.com/ehids/ecapture/issues/69
add nosearch argument to skip the auto search of tls libs when
in container that `/etc/ld.so.conf` and standard lib path like
` /lib64`, `/usr/lib64` do not exist
Signed-off-by: Vincent Li <vincent.mc.li@gmail.com>
=> Add nosearch argument to skip auto search lib path

.github/ISSUE_TEMPLATE/bug_report.md, main.go
=> fixed: outputing blank text on linux 4.18 #81

cli/cmd/tls.go, kern/bash_kern.c, kern/gnutls_kern.c, kern/nspr_kern.c, kern/openssl_kern.c, user/probe_openssl.go
event filter by uid for tls module #85
=> New feature: #85 event filter by uid for module tls

README.md, README_CN.md, cli/cmd/root.go
Add chinese name 旁观者, means:[当局者迷，旁观者清](https://en.wiktionary.org/wiki/%E7%95%B6%E5%B1%80%E8%80%85%E8%BF%B7%EF%BC%8C%E6%97%81%E8%A7%80%E8%80%85%E6%B8%85)
=> Add chinese name 旁观者.

.github/workflows/go-c-cpp.yml, .github/workflows/release.yml, pkg/util/ebpf/bpf_linux.go, pkg/util/ebpf/bpf_test.go
=> pkg : fix Kernel config read failed, error:Config not found #117

.github/workflows/go-c-cpp.yml, .github/workflows/release.yml, main.go, pkg/util/ebpf/bpf_androidgki.go, pkg/util/ebpf/bpf_linux.go, pkg/util/ebpf/bpf_test.go
remove detection of BPF config when running at container.
In Github Action release.yml , qemu in docker ,do not have BPF config , eCapture cant works with ecapture -h.
other issue : #117
=> ebpf: remove detection of BPF config when running at container #127

cli/cmd/bash.go, cli/cmd/mysqld.go, cli/cmd/postgres.go, cli/cmd/tls.go, pkg/event_processor/base_event.go, pkg/event_processor/ievent.go, user/event_bash.go, user/event_gnutls.go, user/event_gossl.go, user/event_mysqld.go, user/event_nspr.go, user/event_openssl.go, user/event_postgres.go, user/imodule.go
=> all : refactor event_processor EventType.

cli/cmd/tls.go, user/imodule.go, user/probe_openssl.go
=> cli/cmd : clean up all probe while process exit. (#150)

cli/cmd/tls.go, go.mod, go.sum, kern/common.h, kern/ecapture.h, kern/openssl_tc.h, user/config_openssl.go, user/probe_openssl.go, user/probe_openssl_tc.go
=> user : Support writing pcapng files with Decryption Secrets Block (DSB).

kern/common.h
=> kern : define variable target_port always.

cli/cmd/tls.go, user/imodule.go, user/probe_bash.go, user/probe_gnutls.go, user/probe_gossl.go, user/probe_mysqld.go, user/probe_nspr.go, user/probe_postgres.go
=> user : tls models exit gracefully.

Makefile, kern/masterkey_kern.h
=> kern : support boringssl offset for Android 12.

kern/masterkey_kern.h, pkg/util/hkdf/hkdf.go, user/module/probe_openssl.go
PR to fix TLSv1.3-related issues.
I use ecapture to hook `libssl` used by an NGINX server, not the client side `libssl`.
Then I found that neither the written key log file nor PcapNG with DSB could decrypt the TLS 1.3 traffic. 
Environment:
1. NGINX with OpenSSL 1.1.1n
2. Cipher suites: TLS_AES_256_GCM_SHA384
3. curl compiled with `USE_CURL_SSLKEYLOGFILE` enabled
Issues I found and fixed:
1. write `SERVER_HANDSHAKE_TRAFFIC_SECRET` instead of a second `CLIENT_HANDSHAKE_TRAFFIC_SECRET` to the key log file
2. uses Hash function found in cipher_id of the master key event in `expandLabel` function
After fixed the above issues, still couldn't decrypt the TLS 1.3 traffic. In key log file, client_randoms are the same for both key log file. But four values are all different.
Possible issues I …
=> Fix: correct ssl_st member offsets

kern/masterkey_kern.h, kern/openssl_tc.h, pkg/event_processor/http_response.go
=> Boringssl decrypt failed

kern/masterkey_kern.h, user/module/probe_openssl_tc.go
fixes: #187 
SSL_SESSION *SSL_get_session(const SSL *ssl) from boringssl src/ssl/ssl_session.cc
```c++
SSL_SESSION *SSL_get_session(const SSL *ssl) {
// Once the handshake completes we return the established session. Otherwise
// we return the intermediate session, either |session| (for resumption) or
// |new_session| if doing a full handshake.
if (!SSL_in_init(ssl)) {
return ssl->s3->established_session.get();
}
SSL_HANDSHAKE *hs = ssl->s3->hs.get();
if (hs->early_session) {
return hs->early_session.get();
}
if (hs->new_session) {
return hs->new_session.get();
}
return ssl->session.get();
}
```
=> kern: get ssl_session in the `*SSL_get_session()` order .  

pkg/event_processor/iworker.go, pkg/event_processor/processor.go, pkg/event_processor/processor_test.go, user/module/imodule.go, user/module/probe_bash.go, user/module/probe_gnutls.go, user/module/probe_gossl.go, user/module/probe_mysqld.go, user/module/probe_nspr.go, user/module/probe_openssl.go, user/module/probe_postgres.go
=> user/module : hex model output.

user/module/const_androidgki.go, user/module/const_linux.go, user/module/probe_openssl_tc.go
fixes:#212
1. SSL_do_handshake for Android.
2. SSL_write for Linux
`SSL_do_handshake` was null sometimes on Linux .
=> user/module : use const for SSL masterKey function hook.

kern/common.h, kern/openssl_tc.h
fixes : #222
.rodata: map create: read- and write-only maps not supported
=> kern: rodata map not supported on kernel 4.19 or older

pkg/event_processor/http_request.go, pkg/event_processor/iparser.go, pkg/event_processor/iworker.go, pkg/event_processor/processor.go
=> kern: http2 response packet decode failed.

kern/masterkey_kern.h, user/module/probe_openssl.go
fixes: #231
Co-Authored-By: blaisewang <blaisewang@icloud.com>
=> kern: capture master secrets for tls 1.3

Makefile, kern/boringssl_masterkey.h, kern/common.h, kern/openssl_3_0_0_kern.c, kern/openssl_3_0_1_kern.c, kern/openssl_3_0_2_kern.c, kern/openssl_3_0_3_kern.c, kern/openssl_3_0_4_kern.c, kern/openssl_3_0_5_kern.c, kern/openssl_3_0_6_kern.c, kern/openssl_masterkey.h, kern/openssl_masterkey_3.0.h, user/module/const.go, user/module/probe_openssl.go, user/module/probe_openssl_lib.go, utils/openssl_3_0_offset.c, utils/openssl_offset_3.0.sh
=> feat : support openssl 3.0

.github/workflows/codeql-analysis.yml, .github/workflows/go-c-cpp.yml, .github/workflows/release.yml, Makefile, README.md, README_CN.md, builder/Makefile.release
also set mininum kernel as 5.4 (ubuntu 20.04) for x86_64 arch.
=> workflows :  release Android x86_64 use nocore model.

kern/common.h, user/module/imodule.go, user/module/probe_openssl.go
with the asm method, the constant value has to be of type uint64
=> constant value has to be of type uint64 (#261)

builder/gen_android_nocore.sh, builder/inint_env.sh
=> builder: add curl shell to install develop environment.

Makefile, kern/boringssl_1_1_1_kern.c, kern/boringssl_const.h, kern/boringssl_masterkey.h, kern/openssl_1_0_2a_kern.c, kern/openssl_1_1_0a_kern.c, kern/openssl_1_1_1a_kern.c, kern/openssl_1_1_1b_kern.c, kern/openssl_1_1_1d_kern.c, kern/openssl_1_1_1j_kern.c, kern/openssl_3_0_0_kern.c, user/event/event_masterkey.go, user/module/const.go, user/module/probe_openssl.go, user/module/probe_openssl_tc.go, utils/boringssl-offset.c, utils/boringssl_offset_1.1.1.sh, utils/openssl_1_0_2_offset.c, utils/openssl_1_1_0_offset.c, utils/openssl_1_1_1_offset.c, utils/openssl_3_0_offset.c, utils/openssl_offset_1.0.2.sh, utils/openssl_offset_1.1.0.sh, utils/openssl_offset_1.1.1.sh, utils/openssl_offset_3.0.sh
fixes #283 
On an android phone, after triggering network behavior, many null-valued keys were captured. 
Here, the problem of offset address calculation error is fixed, and the detection of TLS handshake state is increased.
=> Tls 13 masterkey is taken wrong (fixes #283)

pkg/proc/proc.go
=> pkg: get GoVersion by `buildinfo` package from ELF (by golang compiled)  (#262)

user/module/const.go, user/module/imodule.go
improved event lost.
> perf event ring buffer full
change 64 to 1024. in Linux, will be 4K * 1024 = 4M. 
improve #291 , #314
=> user : increase buffer size of ebpf map. (improve #291 , #314)

kern/bpf/bpf_tracing.h
=> kern: fix typo in bpf_tracing.h

README.md, README_CN.md, README_JA.md
Japanese translated README is added.
=> Add JA readme

rpmBuild.spec, rpm_build.sh
now we can use a simple command to build rpm: `sh rpm_build.sh`, it makes the ecapture installed more convenient.
output of `rpm -qi ecapture` when ecapture is installed is as follows:
=> support rpm build

Makefile, builder/rpmBuild.spec, builder/rpm_build.sh
optimize the way to build rpm, now we can use `make rpm VERSION=0.5.0 RELEASE=2` to generate rpm
=> use makefile to build rpm

user/module/probe_openssl.go
However, we need to identify the root cause. The TLS key length cannot exceed 48 bytes.
=> user: fixes slice out of range (#363)

pkg/event_processor/http_request.go, pkg/event_processor/http_response.go, pkg/event_processor/iworker.go
=> Tls response unexpected eof

pkg/util/ebpf/bpf_linux.go, pkg/util/ebpf/bpf_test.go
pkg/util/util/ebpf/bpf_linux.go, func isCOntainerCgroup is Non standard, modify it
=> modify func isCOntainerCgroup to isContainerCgroup, and where referenced

README.md, README_CN.md, README_JA.md, cli/cmd/gotls.go, cli/cmd/tls.go, user/config/config_gnutls.go, user/config/config_gnutls_linux.go, user/config/config_nspr.go, user/config/config_nspr_linux.go, user/config/config_openssl.go, user/config/config_openssl_linux.go, user/config/iconfig.go, user/module/probe_gnutls.go, user/module/probe_nspr.go, user/module/probe_openssl.go, user/module/probe_openssl_tc.go
remove `Curlpath` flag from gnutls library.
remove `Firefoxpath` flag from nspr library.
remove `Curlpath` flag from openssl library.
=> refactor: removal of deprecated flag support.

kern/boringssl_1_1_1_kern.c, kern/openssl.h, kern/openssl_1_0_2a_kern.c, kern/openssl_1_1_0a_kern.c, kern/openssl_1_1_1a_kern.c, kern/openssl_1_1_1b_kern.c, kern/openssl_1_1_1d_kern.c, kern/openssl_1_1_1j_kern.c, kern/openssl_3_0_0_kern.c, user/module/imodule.go, user/module/probe_openssl.go, utils/boringssl-offset.c, utils/openssl_1_0_2_offset.c, utils/openssl_1_1_0_offset.c, utils/openssl_1_1_1_offset.c, utils/openssl_3_0_offset.c, utils/openssl_offset_1.1.0.sh, utils/openssl_offset_1.1.1.sh
utils : create BIO_ST_NUM const used bio_st->num
=> fix : OpenSSL's file descriptor is always 0

user/module/const.go, user/module/const_androidgki.go, user/module/const_linux.go, user/module/probe_openssl.go
Optimize the ebpf map buffer size applied on the Android system, changing it from 10M to 1M.
=> fix : out of silice range.

kern/openssl.h, kern/openssl_masterkey.h, kern/openssl_masterkey_3.0.h, kern/tc.h, user/module/probe_openssl.go
This block of logic will be used when wbio's FD is empty.
=> bugfix: Hook the ssl_set_fd function to get FD.

kern/bash_kern.c, kern/boringssl_masterkey.h, kern/gnutls_kern.c, kern/gotls_kern.c, kern/mysqld_kern.c, kern/nspr_kern.c, kern/postgres_kern.c, kern/tc.h
=> improve: add missing eBPF maps parameters.

cli/cmd/tls.go, kern/tc.h, pkg/proc/proc.go
当使用**pcapng**模式时，如果`--port`参数为0，则支持所有端口的网络包捕获。否则则只捕获`--port`对应的端口数据。默认是`443` 端口。
`--port`默认没有捕获所有网络包，是因为有很多场景，主机的网络流量很大，eBPF的map写入太快，用户空间消费过慢，导致丢包的问题。虽然用户空间在创建eBPF map时，已经申请了`BufferSizeOfEbpfMap`大的内存，但仍然还存在网络包过多导致数据丢失的可能。 而且，在Android上有内存大小限制，`BufferSizeOfEbpfMap`的值仅为`1024`。
------------------------------------------------------------------------------------------------
When using **pcapng** mode, if the `--port` parameter is set to 0, it supports capturing network packets from all ports. Otherwise, it only captures data from the port corresponding to `--port`. The default port is 443. 
The reason why `--port` does not capture all network packets by default is that in many scenarios, the host's network traffic is high and eBPF map writes too fast while user space consumption is slow, …
=> supports all ports when target_port is 0

.github/workflows/codeql-analysis.yml, .github/workflows/go-c-cpp.yml, .github/workflows/release.yml, Makefile, README.md, README_CN.md, README_JA.md, builder/init_env.sh, go.mod, go.sum, main.go
update ebbpfmanager to v0.4.4
update cilium/ebpf to v0.12.3
=> update golang version to 1.21 from 1.18

user/event/event_gnutls.go, user/event/event_mysqld.go, user/event/event_nspr.go, user/event/event_openssl.go, user/event/event_postgres.go, user/event/misc.go
`DecodeKtime()` snippet is take from tetragon. [Refer](https://github.com/cilium/tetragon/blob/c4ea0e76d6cf5fcc33d8977796d829a98572d531/pkg/ktime/ktime.go#L39)
=> Decode kernel time to user time

user/module/probe_openssl.go
fix #416
修复openssl 事件 hex模式无效的问题.
=> Fix ： openssl event output invalid with hex mode 

user/config/config_gotls.go
Currently ecapture fails for stripped go binaries.
Because in `findRetOffsets()` method, only symbols from `sym table section` are consider for searching of `GoTlsReadFunc symbol`. Since in case of stripped go binaries no `sym table section` is present, ecapture fails to initialise.
This PR adds dynamic symbols in search space to fix the issue.
fixes #428
=> Add support for stripped go binaries

cli/cmd/gnutls.go, cli/cmd/nss.go, cli/cmd/root.go, tests/golang_https.go
as #433 , split modules, optimize memory usage.
=> splitting gnutls/nss module from tls module lists.

cli/cmd/bash.go, cli/cmd/global.go, cli/cmd/gnutls.go, cli/cmd/gotls.go, cli/cmd/mysqld.go, cli/cmd/nss.go, cli/cmd/postgres.go, cli/cmd/root.go, cli/cmd/tls.go, user/config/common_androidgki.go, user/config/common_linux.go, user/config/config_bash.go, user/config/config_gnutls.go, user/config/config_gotls.go, user/config/config_mysqld.go, user/config/config_nspr.go, user/config/config_nspr_linux.go, user/config/config_openssl.go, user/config/config_postgres.go, user/config/iconfig.go, user/module/const_androidgki.go, user/module/const_linux.go, user/module/imodule.go
used `--map-size` to set mapSize perCPU in cli. default:10240KB,
=> user: custom mapSize flag. improve memory usage #433 .

CHANGELOG.md, README.md, README_CN.md, README_JA.md, cli/cmd/global.go, cli/cmd/gotls.go, cli/cmd/root.go, cli/cmd/tls.go, user/config/config_gotls.go, user/config/config_openssl.go, user/config/config_openssl_androidgki.go, user/config/config_openssl_linux.go, user/config/iconfig.go, user/module/imodule.go, user/module/probe_gotls.go, user/module/probe_gotls_keylog.go, user/module/probe_gotls_pcap.go, user/module/probe_gotls_text.go, user/module/probe_openssl.go, user/module/probe_openssl_keylog.go, user/module/probe_openssl_pcap.go, user/module/probe_openssl_text.go
add the `model` flag to distinguish the captured modes,
including `text`, `pcapng/pcap`, and `keylog/key`.
Support two modules: **gotls** and **openssl**.
Co-Authored-By: blaisewang <blaisewang@icloud.com>
=> add the `model` flag to distinguish the captured modes, support keylog captured.

CHANGELOG.md, cli/cmd/root.go
Sometimes, the default size in Linux is 4MB.
=> cli: reduce mapsize to 1024 * PAGESIZE.

pkg/util/ebpf/bpf.go, pkg/util/ebpf/bpf_androidgki.go, pkg/util/ebpf/bpf_linux.go, pkg/util/ebpf/bpf_test.go
fix: #445 
Added detection of Android running on containers
```shell
cda5a878a8c4:/ # ./ecapture tls
2023/12/23 14:37:30 Your environment is like a container. We won't be able to detect the BTF configuration.
tls_2023/12/23 14:37:30 ECAPTURE :: ecapture Version : androidgki_x86_64:--:5.15.0-91-generic
tls_2023/12/23 14:37:30 ECAPTURE :: Pid Info : 1717
tls_2023/12/23 14:37:30 ECAPTURE :: Kernel Info : 5.15.126
tls_2023/12/23 14:37:30 EBPFProbeOPENSSL	module initialization
tls_2023/12/23 14:37:30 EBPFProbeOPENSSL	master key keylogger:
tls_2023/12/23 14:37:30 ECAPTURE ::	Module.Run()
tls_2023/12/23 14:37:30 EBPFProbeOPENSSL	Text MODEL
tls_2023/12/23 14:37:30 EBPFProbeOPENSSL	OpenSSL/BoringSSL version not found, used default version :android_default
tls_2023/12/23 14:37:30 EBPFProbeOPENSSL …
```
=> pkg: support android on docker.

cli/cmd/gotls.go, cli/cmd/tls.go, user/module/imodule.go, user/module/probe_gotls.go, user/module/probe_gotls_pcap.go, user/module/probe_openssl.go, user/module/probe_openssl_pcap.go, user/module/probe_pcap.go
Optimized the pcapng file writing mechanism, flash every two seconds.
=> user: improve pcapng writer, flush every 2s.

.github/workflows/release.yml, README.md, builder/Makefile.release
Added packaging eCapture into deb format using non-CO-RE eBPF bytecode format for better compatibility with Ubuntu kernels that do not have BTF enabled. Automatically uploads deb package during eCapture release.
=> builder: add debian package build script.

Makefile, builder/Makefile.release
Optimize the feature list for the Android version retaining the three essential modules: openssl, broingssl, and gotls. 
Exclude BPF bytecode for kernels with an architecture smaller than arm64 and versions less than 5.2.
=> makefile: Optimize the feature list for the Android version

user/event/event_openssl.go, user/module/imodule.go
Decode the content of an OpenSSL event.
=> user: support event processor

user/module/probe_openssl_lib.go, utils/openssl_offset_1.0.2.sh, utils/openssl_offset_3.1.sh
Since 3.0.x has the same offsets as the other properties of the 3.1.x series ssl_st structs, the 3.0.x kern file is used uniformly.
=> utils: support openssl 3.1.0-3.1.4 and 3.0.9-3.0.12

tests/issue_463/Makefile, tests/issue_463/main.c, tests/issue_463/readme.md, user/module/const.go, user/module/probe_openssl.go, user/module/probe_openssl_keylog.go, user/module/probe_openssl_pcap.go, user/module/probe_openssl_text.go
* 为了读取到TLS握手完成后的client_random等密钥，必需要选择一个合适的HOOK函数。
* SSL_write\SSL_read时，TLS握手是建立完成的，但调用过于频繁，会带来性能问题，参见 #463
* 综合来看，合适的HOOK函数需要满足以下几个条件:
1. 函数是在TLS握手完成后调用
2. 函数名在动态链接库的符号表中是导出状态
3. 函数是低频调用
* 在 openssl 类库中，以客户端角色调用 `SSL_connect` 或者以服务端角色 `SSL_accept` ，最终都会进入 `ssl/statem/statem.c` 的 `state_machine` 函数进行TLS握手。
* 所以，可选范围是在这个函数内以大写`SSL`开头的函数。
* 当使用openssl的方式为`同步`调用时，TLS握手成功会返回1，也就是`ret = 1`，即需要在这个变量赋值后，被调用的函数，才能拿到符合要求的内存数据。 `state_machine`函数内符合要求的就只有`SSL_get_wbio`了。
* 当使用openssl的方式为`异步 (BIO)`调用时，还需要增加`SSL_in_before`函数。
------
* In order to read the client_random and other keys after TLS handshake is completed, it is necessary to select a suitable HOOK function.
* When SSL_write\SSL_read, the TLS handshake is already established, but calling it too frequently will cause performance issues, see …
=> user: imporve #463, impact on the performance of the tested program

user/module/probe_gotls.go
* initialize tcPacketsChan in MTCProbe of GoTLSProbe
* filled mod.name and mod.mType in probe_gotls.go::init() used for debugging
The problem mentioned in issure #492 is caused by uninitialized ` tcPacketsChan` in `GoTLSProbe`.
When [code](https://github.com/gojue/ecapture/blob/2127596005116087f13a8d25b382d5bc4b56dd96/user/module/probe_pcap.go#L251) is executed, `eOverflow` is returned which turn out to be the error message mentioned in issue #492
=> Fix: init GoTLSProbe.tcPacketsChan #492

.github/workflows/go-c-cpp.yml, pkg/event_processor/http_request.go, pkg/event_processor/http_response.go, pkg/event_processor/processor.go
When add -race to `go test` , several data race warnings are raised.
first one(data race for `workerqueue` in `EventProcessor`):
```bash
WARNING: DATA RACE
Read at 0x00c000098c30 by goroutine 7:
ecapture/pkg/event_processor.(*EventProcessor).Close()
/home/rtzhong/ecapture/pkg/event_processor/processor.go:118 +0xb04
ecapture/pkg/event_processor.TestEventProcessor_Serve()
/home/rtzhong/ecapture/pkg/event_processor/processor_test.go:77 +0xb29
testing.tRunner()
/usr/local/go/src/testing/testing.go:1689 +0x21e
testing.(*T).Run.gowrap1()
/usr/local/go/src/testing/testing.go:1742 +0x44
Previous write at 0x00c000098c30 by goroutine 9:
runtime.mapdelete_faststr()
/usr/local/go/src/runtime/map_faststr.go:301 +0x0
ecapture/pkg/event_processor.(*EventProcessor).delWorkerByUUID() …
```
=> add -race flags for `go test` and fix data race warning

kern/openssl.h
make the format of uuid consistent with SSL_read, get the fd rather than a random value
=> openssl: encode the value of fd (ssl->wbio->num) to gen uuid, rather than an unexpected random number

pkg/event_processor/iworker.go, pkg/event_processor/processor.go, pkg/event_processor/processor_test.go
* add `IfUsed()` for worker to check if it is used.
* add `Get()` for  routine that generates event before using the worker and `Put()` when after using the worker. They should not be called concurently(only one producer). So it panics if unexpected behavior happen. 
* add clean up logic for ew.incoming and return only after both the ew.incoming is empty and  ew is not used. 
The reasoning for that is as follows.
When returned from ew.Close(), there are two possiblities:
1) no routine can touch it.
2) one routine can still touch ew because getWorkerByUUID()
**happen before** ew.Close()
When no routine can touch it (i.e.,ew.IfUsed == false),
we just drain the ew.incoming and return.
When one routine can touch it (i.e.,ew.IfUsed == true), we ensure
that we only return after the routine can …
=> fix #500 to avoid potential hang and event loss

kern/bash_kern.c, kern/common.h, user/event/event_bash.go, user/module/imodule.go, user/module/probe_bash.go
Here, I try to address the problem in #490 with smaller change to the code.
The following command can be detected:
```bash
exec ls
```
```bash
if echo hello;
then echo world
fi
```
```bash
exec ls
```
```bash
exit
```
However, the following command have problem and it can be improved.
```bash 
exec ls \ 
/usr/bin
```
```bash
command \
exec \
final
```
I will try to improve this in later time. For now, it is a draft.
=> tentative fix to address bash problem #490

user/config/config_gotls.go
fixup: #512
details： wlingze#2， #514
=> [Fix] get textStart from pclnTable

user/config/config_gotls.go
fix  PR  #516
On amd64, when the executable program in PIE format compiled by golang reads the return instruction of the function, the start address of inst is incorrect, resulting in an exception, see PR #516 for details.
ref: https://github.com/golang/go/blob/bdd27c4debfb51fe42df0c0532c1c747777b7a32/src/cmd/internal/objfile/elf.go#L175
=> fix: amd64, offset read error issue for PIE executable. PR #516

.github/workflows/go-c-cpp.yml, .github/workflows/release.yml, README.md, README_CN.md, README_JA.md, functions.mk, variables.mk
Fix bug that prevents compiling `jschwinger233/elibpcap` package during cross-compilation.
```shell
/home/cfc4n/project/ecapture $ CROSS_ARCH=amd64 make
make[1]: Leaving directory '/home/cfc4n/project/ecapture/lib/libpcap'
CGO_CFLAGS='-O2 -g -gdwarf-4 -I/home/cfc4n/project/ecapture/lib/libpcap/' CGO_LDFLAGS='-O2 -g -L/home/cfc4n/project/ecapture/lib/libpcap/ -lpcap -static' GOOS=linux GOARCH=amd64 CC=clang go build -tags linux -ldflags "-w -s -X 'ecapture/cli/cmd.GitVersion=linux_amd64:0.7.5-20240303-bfb4a8c:[CORE]' -X 'main.enableCORE=true' " -o bin/ecapture
file bin/ecapture
../../go/pkg/mod/github.com/jschwinger233/elibpcap@v0.0.0-20231010035657-e99300096f5e/elibpcap.go:25:22: undefined: CompileEbpf
bin/ecapture: cannot open `bin/ecapture' (No such file or directory)
```
```shell …
```
=> makefile: used CC=$(CROSS_COMPILE)gcc for CGO compile.

kern/openssl_masterkey.h, user/module/probe_openssl_lib.go
Fixes #533 
The root cause of the problem was that the offset of the client_random member within the `ssl3_state_st` structure varies across different OpenSSL versions.
Although the offsets for the `ssl3_state_st->client_random` member (`SSL3_STATE_ST_CLIENT_RANDOM`) were already generated for all supported OpenSSL versions, but they were not being utilized correctly.
﻿
To solve this issue, the existing `SSL3_STATE_ST_CLIENT_RANDOM` offsets have been integrated into the code, ensuring that ecapture can accurately retrieve the `client_random` value from the correct location within the `ssl3_state_st` structure, regardless of the OpenSSL version being used.
=> Fix keylog mode not working correctly on certain OpenSSL versions

.github/workflows/go-c-cpp.yml, .github/workflows/release.yml
about github action context {github.ref_name}:https://docs.github.com/en/actions/learn-github-actions/contexts#github-context:
> The short ref name of the branch or tag that triggered the workflow run. This value matches the branch or tag name shown on GitHub. 
For example, feature-branch-1.For pull requests, the format is <pr_number>/merge.
=> workflows: change steps.get_tags.outputs.VERSION to github.ref_name

builder/init_env.sh, cli/cmd/root.go, variables.mk
Run the `make prepare` command only if the `arch/$(LINUX_ARCH)/kernel/asm-offsets.s` file does not exist. This is because this file is generated during the make phase.
```shell
CC      kernel/bounds.s
CC      arch/x  86/kernel/asm-offsets.s
CALL    scripts/checksyscalls.sh
CALL    scripts/atomic/check-atomics.sh
```
```shell
CC      kernel/bounds.s
UPD     include/generated/bounds.h
CC      arch/arm64/kernel/asm-offsets.s
UPD     include/generated/asm-offsets.h
CALL    scripts/checksyscalls.sh
CALL    scripts/atomic/check-atomics.sh
```
=> makefile: Optimized the generation mechanism of kernel header files

.github/workflows/release.yml, README.md, README_CN.md, README_JA.md, builder/Dockerfile
This PR provides a way to run ecapture containerized. for better deployment in the background.
Specifically, a docker image will be built and uploaded to dockerhub at release tag time
I have done some simple tests, and ecapture works fine:
```shell
bash:
sudo docker run --rm --privileged=true -v /usr/bin/bash:/usr/bin/bash sancpp/ecapture bash --bash="/usr/bin/bash"
gotls:
sudo docker run --rm --privileged=true --net=host -v  ${HOME}/test/test_gotls:/test sancpp/ecapture gotls --elfpath="/test/main" --hex
tls:
sudo docker run --rm --privileged=true --net=host -v /etc:/etc -v /usr:/usr -v ${PWD}:/output sancpp/ecapture tls -m pcap -i wlp3s0 --pcapfile=/output/ecapture.pcapng tcp port 443
mysqld:
sudo docker run --rm -v mysqld-file:/usr/sbin --name mysql_test -e MYSQL_ROOT_PASSWORD=123456 …
```
=> add dockerfile

.github/workflows/go-c-cpp.yml, cli/http/server.go, cli/http/server_androidgki.go, cli/http/server_linux.go
```shell
cli/http/server.go:93:27: undefined: config.MysqldConfig
cli/http/server.go:103:27: undefined: config.PostgresConfig
bin/ecapture: cannot open `bin/ecapture' (No such file or directory)
```
=> cli: fix undefined: config.MysqldConfig. (fix #548)

user/module/imodule.go, user/module/probe_openssl.go
=> user: fix #553, `hashLen` is not allowed to be more than 64 bytes

kern/boringssl_na_kern.c, user/module/probe_openssl_lib.go, utils/boringssl_non_android_offset.sh, variables.mk
feat: #552
You should know that the version management of boringssl is chaotic, divided into Android version and non-Android version, corresponding to two different code repositories. Also, the `OPENSSL_VERSION_TEXT` content has not been modified and remains unchanged. It is impossible to distinguish versions based on this field.
Therefore, if you expect eCapture to better support the non-Android boringssl, you need to confirm the version matching situation by yourself. When necessary, you will need to patch it yourself.
Android Boringssl: https://android.googlesource.com/platform/external/boringssl/
Non-Android Boringssl: https://boringssl.googlesource.com/boringssl aka https://github.com/google/boringssl
=> kern: Support for the non-Android boringssl library has been added.

cli/cmd/tls.go, kern/openssl.h, kern/tc.h, user/config/config_openssl.go, user/config/config_openssl_androidgki.go, user/config/config_openssl_linux.go, user/event/event_openssl.go, user/module/probe_openssl.go, user/module/probe_openssl_text.go
use kprobe `__sys_connect` inseated uprobe `connect`.
remove `libPthread.so`.
=> use kprobe/__sys_connect inseated uprobe/connect.

pkg/util/ebpf/bpf.go
There are several paths to obtain current kernel config on Linux:
1. `/proc/config.gz`: available since Linux 2.6 and needs `CONFIG_IKCONFIG_PROC=y`;
2. `/boot/config` and `/boot/config-%s`: available in most Debian-based distros, but NOT in Arch Linux or Gentoo.
However, for those kernels where `CONFIG_IKCONFIG_PROC` is not set, both of them are unavailable. According to [proc(5)](https://man7.org/linux/man-pages/man5/proc.5.html), the kernel config can be found at `/lib/modules/$(uname -r)/build/.config`. 
This PR adds it to the search paths.
**Q: Is there really any kernel that is compiled without `CONFIG_IKCONFIG_PROC`?**
Yes. [Xanmod](https://xanmod.org) is a popular kernel among users which [does not have `CONFIG_IKCONFIG` enabled](https://gitlab.com/xanmod/linux/-/blob/6.9/CONFIGS/x …
=> add possible linux kernel config path

pkg/event_processor/http_response.go
fix:
```
bin/ecapture tls -m text
curl -I --http1.1  https://www.google.com/
......
2024-06-18T10:19:58+08:00 INF UUID:104243_104243_curl_0_1_0.0.0.0, Name:HTTPRequest, Type:1, Length:75
HEAD / HTTP/1.1
Host: www.google.com
Accept: */*
User-Agent: curl/7.88.1
2024/06/18 10:19:58 [http response] DumpResponse error: unexpected EOF
......
```
=> fix: DumpResponse error in HEAD request

pkg/event_processor/http_request.go, pkg/event_processor/http_response.go
this is the extend of #572 .
The request/response body may be truncated in events, so the 'Content-Length' header value not match the real data length, ReadAll/Close will always raise UnexpectedEOF error.  #572 can only fix the real data length is 0, the pr will fix the others.
=> fix: truncated body dump error

kern/openssl_1_0_2a_kern.c, kern/openssl_1_1_0a_kern.c, kern/openssl_1_1_1a_kern.c, kern/openssl_1_1_1b_kern.c, kern/openssl_1_1_1d_kern.c, kern/openssl_1_1_1j_kern.c, kern/openssl_3_0_0_kern.c, kern/openssl_3_2_0_kern.c, user/module/probe_openssl_lib.go, utils/openssl_1_0_2_offset.c, utils/openssl_1_1_0_offset.c, utils/openssl_1_1_1_offset.c, utils/openssl_3_0_offset.c, utils/openssl_3_2_0_offset.c, utils/openssl_offset_3.1.sh, utils/openssl_offset_3.2.sh, utils/openssl_offset_3.3.sh
Add the offset of the `ssl_st->server` field to determine whether the current *SSL is in server mode.
=> kern: support openssl 3.3.*

Makefile, kern/common.h, kern/ecapture.h, kern/tc.h
=> feat: allow capture ipv6 packet

.github/codecov.yml, .github/workflows/codeql-analysis.yml, .github/workflows/go-c-cpp.yml, cli/cmd/root.go, user/config/iconfig.go, user/module/imodule.go, user/module/probe_bash.go, user/module/probe_gnutls.go, user/module/probe_gotls.go, user/module/probe_gotls_keylog.go, user/module/probe_gotls_pcap.go, user/module/probe_mysqld.go, user/module/probe_nspr.go, user/module/probe_openssl.go, user/module/probe_postgres.go
Distinguish between program operation logs and captured events; 
in the future, events will be read from the logger to generate HAR format records.
=> user: split loggers, which are divided into loggers and event collectors

kern/tc.h
=> fix: fix undeclared identifier error when make in debug mode

user/module/imodule.go
=> user: adjusted the timing of the display of the kernel version is too low

kern/mysqld_kern.c, kern/postgres_kern.c, kern/tc.h, user/module/probe_openssl_pcap.go
remove uid/pid filter in kprobe/tcp_sendmsg.
tcp_sendmsg hook all processes are monitored, so there is no need to filter pid and uid, otherwise pid\uid cannot be used in the TC capture_packets function to filter network packets
=> kern: support uid/pid filter in ebpf TC hook.

user/module/probe_openssl_lib.go
Android 回退到默认版本时的日志等级是 warn，但 linux 还是 info。
=> fix: fallback to default version with warn

.gitignore, functions.mk
Fix #604
Signed-off-by: Manjusaka <me@manjusaka.me>
=> chore: Use `-tags 'netgo'` in bulding process to avoid SIGSEGV because of the different version of glibc in dfferent Linux distros

.github/workflows/codeql-analysis.yml, .github/workflows/go-c-cpp.yml, .github/workflows/release.yml, COMPILATION.md, COMPILATION_CN.md, README_JA.md, builder/init_env.sh, variables.mk
error output:
```shell
Reading state information...
E: Unable to locate package linux-source-6.8.0
E: Couldn't find any package by glob 'linux-source-6.8.0' E: Couldn't find any package by regex 'linux-source-6.8.0' Error: Process completed with exit code 100.
```
Github Action run failed via : https://github.com/gojue/ecapture/actions/runs/11101523778/job/30839371311?pr=642#step:3:48
The [Ubuntu 22.04 image](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md) used by Github Action has a system kernel version of `6.8.0-1014-azure`, but there is no package for `linux-source-6.8.0` in the deb repository. The deb package downloaded from `apt install linux-source` corresponds to a kernel version of `5.15`, which is quite frustrating.
---- 
Github Action …
=> workflows: update linux source tgz file version.

kern/bash_kern.c, kern/boringssl_masterkey.h, kern/common.h, kern/gnutls_kern.c, kern/gotls_kern.c, kern/mysqld_kern.c, kern/nspr_kern.c, kern/openssl_3_2_0_kern.c, kern/openssl_3_2_3_kern.c, kern/openssl_3_3_0_kern.c, kern/openssl_masterkey.h, kern/openssl_masterkey_3.0.h, kern/openssl_masterkey_3.2.h, user/module/probe_gotls_text.go, utils/boringssl-offset.c, utils/openssl_1_0_2_offset.c, utils/openssl_1_1_0_offset.c, utils/openssl_1_1_1_offset.c, utils/openssl_3_0_offset.c, utils/openssl_3_2_0_offset.c, variables.mk
=> fix the issue with retrieving the return value of the Read function in the Golang TLS module.

Makefile, builder/Dockerfile, builder/init_env.sh, variables.mk
via [github action (docker build)](https://github.com/gojue/ecapture/actions/runs/11208092161/job/31151556985#step:7:3409)
```shell
clang \
#18 8.403 		-emit-llvm -O2 -S -D__TARGET_ARCH_x86 -xc -g -isystem -D__BPF_TRACING__ -D__KERNEL__ -DNOCORE -nostdinc -DKBUILD_MODNAME=\"eCapture\" -target x86_64  -Wall -Wno-unused-variable -Wnounused-but-set-variable -Wno-frame-address -Wno-unused-value -Wno-unknown-warning-option -Wno-pragma-once-outside-header -Wno-pointer-sign -Wno-gnu-variable-sized-type-not-at-end -Wno-deprecated-declarations -Wno-compare-distinct-pointer-types -Wno-address-of-packed-member -fno-stack-protector -fno-jump-tables -fno-unwind-tables -fno-asynchronous-unwind-tables \
#18 8.403 		-I ./kern -I ./kern/bpf/x86 \
#18 8.403 		-I …
```
=> builder: docerk build error: header not found (fix: #649)

kern/boringssl_a_13_kern.c, kern/boringssl_a_14_kern.c, kern/boringssl_na_kern.c, kern/openssl.h, kern/openssl_1_0_2a_kern.c, kern/openssl_1_1_0a_kern.c, kern/openssl_1_1_1a_kern.c, kern/openssl_1_1_1b_kern.c, kern/openssl_1_1_1d_kern.c, kern/openssl_1_1_1j_kern.c, kern/openssl_3_0_0_kern.c, kern/openssl_3_1_0_kern.c, kern/openssl_3_2_0_kern.c, kern/openssl_3_2_3_kern.c, kern/openssl_3_3_0_kern.c, user/event/event_openssl.go, user/module/probe_openssl.go, utils/boringssl-offset.c, utils/openssl_1_0_2_offset.c, utils/openssl_1_1_0_offset.c, utils/openssl_1_1_1_offset.c, utils/openssl_3_0_offset.c, utils/openssl_3_2_0_offset.c
Fixes: #596 
this error happend because application use BIO instead of set socket fd into the SSL layers.
the default fd value in SSLDataEvent struct is 0, When application use SSL_set_fd, the error will not happend, we can get corret fd value.
When application use SSL_set_bio, the fd value in SSLDataEvent struct will keep default value.
App Example:
```
static CURLcode ossl_connect_step1(struct connectdata *conn, int sockindex) {
......
if(!SSL_set_fd(backend->handle, (int)sockfd)) {
/* pass the raw socket into the SSL layers */
failf(data, "SSL: SSL_set_fd failed: %s",
ossl_strerror(ERR_get_error(), error_buffer, sizeof(error_buffer)));
return CURLE_SSL_CONNECT_ERROR;
}
connssl->connecting_state = ssl_connect_2;
return CURLE_OK;
}
static CURLcode ossl_connect_step1(struct Curl_cfilter …
```
=> fix: SSLDataEvent's fd is 0 Error

kern/openssl_3_4_0_kern.c, user/module/probe_openssl_lib.go, utils/openssl_3_2_0_offset.c, utils/openssl_offset_3.4.sh, variables.mk
fix `https://github.com/gojue/ecapture/issues/656` or #656
=> feat(user/module): add ossl version 3.4.0 support

user/module/probe_openssl.go, user/module/probe_openssl_lib.go
Since OpenSSL 3.0, in the built dynamic link library product, the symbols in libssl.so no longer contain the `OPENSSL_VERSION_TEXT` string, causing eCapture to be unable to accurately identify the version of OpenSSL, causing it to fail to work properly. 
For more information please refer to: #675
fix: #609
> openssl 3+（尚未排查出是哪个 commit 导致）不再把版本号放入 libssl.so 的 .rodata 段中，导致自动检测失败从而回落到 openssl 3.0.0。 幸运的是 libcrypto.so 的 .rodata 段中有期望的版本号字符串且 libssl.so 链接到 libcrypto.so，自动获取 libssl 路径时从 libcrypto.so 读取是一个低成本的解决方案。 debian 的 libssl3 包 与 fedora 的 openssl-libs 包会把 libcrypto.so 和 libssl.so 打包在一起，没有查看 alpine 这类更小的发行版是否发生拆分。只能乐观地假设 libssl.so 存在但 libcrypto.so 不存在是不可接受的（环境损坏）。
=> fix(user/module): read version from libcrypto.so

README.md
Suggesting to fix a couple of typos, in particular the spelling of MariaDB
=> fix MariaDB typo in README.md

.github/workflows/release.yml, cli/cmd/root.go, cli/cmd/tls.go, user/module/probe_openssl.go, user/module/probe_openssl_lib.go
=> Fix the version number string cannot be found in the dynamic library of boringssl.

kern/tc.h
The pcap filter now doesn't take effect for packet protocols that are not IP or IPv6, such as ARP.
```
bin/ecapture gnutls -m pcap -i enp0s3  port 443 and not arp
2024-12-04T14:30:59+08:00 INF AppName="eCapture(旁观者)"
2024-12-04T14:30:59+08:00 INF HomePage=https://ecapture.cc
2024-12-04T14:30:59+08:00 INF Repository=https://github.com/gojue/ecapture
2024-12-04T14:30:59+08:00 INF Author="CFC4N <cfc4ncs@gmail.com>"
2024-12-04T14:30:59+08:00 INF Description="Capturing SSL/TLS plaintext without a CA certificate using eBPF. Supported on Linux/Android kernels for amd64/arm64."
2024-12-04T14:30:59+08:00 INF Version=linux_amd64:-20241202-b231985:6.1.0-22-amd64
2024-12-04T14:30:59+08:00 INF Listen=localhost:28256
2024-12-04T14:30:59+08:00 INF eCapture running logs logger=
2024-12-04T14:30:59+08:00 …
```
=> fix: pcap filter not work as expected

cli/cmd/env_detection.go, cli/cmd/root.go, main.go
Without this check, there will be many noisy logs before log "error:operation not permitted", like https://github.com/gojue/ecapture/issues/678#issuecomment-2514532902.
=> feat: detect CAP_BPF

kern/common.h, kern/openssl.h, pkg/event_processor/base_event.go, user/event/event_openssl.go, user/module/probe_openssl.go, user/module/probe_openssl_text.go
It is able to get full 5-tuple info when hooking `connect` and `accept` syscalls with format `saddr:sport-daddr-dport` always.
```bash
$ sudo ./bin/ecapture tls -d
...
2024-12-08T16:44:24Z DBG AddConn success fd=5 pid=113767 tuple=192.168.241.133:37736-172.217.194.113:443
2024-12-10T05:08:04Z DBG AddConn success fd=4 pid=121587 tuple=192.168.241.1:54587-192.168.241.133:8080
...
```
See #682 to get more context.
See [eBPF Talk: 在 bpf 里将 fd 和 sock 关联起来](https://mp.weixin.qq.com/s/sMmudLmn714AmA166TyB_w) for design ideas and technical implementation.
=> feat: Enrich addr info with remote addr info

kern/openssl.h, user/module/probe_openssl_text.go
Fixes #693 
`__sys_connect_file` and `do_accept` are not found on v5.4 kernel.
Then, use `inet_stream_connect` and `inet_accept` instead, as they are found on v4.19 and v5.4 kernels.
I've test it on v5.4, v5.15 and v6.8 kernels.
@cfc4n can you help to test noncore on v4.19 and v5.4 kernels?
=> fix: use other hooks to probe 5-tuple

Makefile, cli/cmd/root.go, cli/cmd/upgrade.go, functions.mk, pkg/upgrade/upgrade_test.go, user/config/iconfig.go, user/module/imodule.go, variables.mk
When compiling eBPF bytecode as non-core, only *_noncore.o files exist in the assets directory. In this case, we can ignore the BTFMode specified in command-line arguments and directly select *_noncore.o files.
=> fix #697, When building in nocore mode, use only non-core bytecode les by default.

cli/cmd/env_detection.go, cli/cmd/root.go
Fixes #706 
It's more simple to check CAP_BPF by capget syscall than creating a bpf prog, as creating bpf prog requires removing rlimit memlock.
=> fix: check CAP_BPF by capget syscall

.github/workflows/release.yml
Github Action `release.yml` run failed in `Release arm64 (CROSS COMPILATION)` phase
```shell
cd lib/libpcap && \
CC=aarch64-linux-gnu-gcc AR=aarch64-linux-gnu-ar CFLAGS="-O2 -g -gdwarf-4 -static -Wno-unused-result" ./configure --disable-rdma --disable-shared --disable-usb \
--disable-netmap --disable-bluetooth --disable-dbus --without-libnl \
--without-dpdk --without-dag --without-septel --without-snf \
--without-gcc --with-pcap=linux \
--without-turbocap --host=aarch64-unknown-linux-gnu && \
CC=aarch64-linux-gnu-gcc AR=aarch64-linux-gnu-ar make
checking build system type... x86_64-pc-linux-gnu
checking host system type... aarch64-unknown-linux-gnu
checking target system type... aarch64-unknown-linux-gnu
checking for aarch64-unknown-linux-gnu-gcc... aarch64-linux-gnu-gcc
checking whether …
```
=> fixed the issue of missing cross-compilation environment.

.github/workflows/release.yml, go.sum
Fix the release notes generation in GitHub Actions workflow by:
1. Using multi-line syntax with EOF delimiter
2. Properly handle special characters and newlines in release notes output
3. Update golang.org/x/net  to v0.33.0
This fixes the error: "Unable to process file command 'output' successfully"
___
Bug fix, Enhancement
___
- Fixed the GitHub Actions workflow for release notes generation by using multi-line syntax with EOF delimiter.
- Addressed issues with handling special characters and newlines in the release notes output.
- Updated the `golang.org/x/net` dependency to version v0.33.0, removing references to the older version.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details> …
=> fix(ci): fix github action release notes generation

Makefile, builder/init_env.sh, functions.mk
1. Fix clean target to properly handle libpcap Makefile existence check
2. Use if statement instead of && operator for better control flow
3. Avoid executing unnecessary commands when libpcap is not present
This change makes the build process more robust and prevents false error reports during cleanup operations.
=> fix(make): improve error handling and clean target logic in Makefile

cli/cmd/env_detection.go
According to the linux man pages: https://man7.org/linux/man-pages/man2/capset.2.html:
> Note that the CAP_* values are bit indexes and need to be bit-shifted before ORing into the bit fields.
And added a check for CAP_SYS_ADMIN permissions.
CLOSE #714
=> fix: incorrect CAP_BPF check method

.github/workflows/go-c-cpp.yml
Use the ARM64 architecture system to run GitHub Actions to avoid the execution time-consuming problem of the Docker QEMU simulator.
refer: https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
=> feat(ci): update GitHub Action runners with Linux arm64 host

kern/openssl.h, user/event/event_openssl.go
=>  feat: support ipv6 4-tuple  (#724)

kern/common.h, pkg/event_processor/base_event.go, pkg/event_processor/processor_test.go, user/event/event_openssl.go
Fix: #740
Increase the memory size for storing SSL data in eBPF to 16K according to the OpenSSL RFC 5246 standard.
=> Fix: #740,  the bug of incomplete SSL data for excessively long lengths.

Makefile, cli/cmd/root.go, pkg/event_processor/iworker.go, pkg/event_processor/processor.go, pkg/event_processor/processor_test.go, user/config/iconfig.go, user/module/imodule.go
=> improve: provide opts to set the truncate size in text mode to reduce memory cost

pkg/event_processor/http2_request.go, pkg/event_processor/http2_response.go
the reason why always has COMPRESSION_ERROR happened: the hpack context lost.
two example:
1. single tcp connection, multi stream on. Before this pr, the hpack DynamicTable is set to 0, so the next headers frame could not be decoded.
run: 
```
nghttp  https://localhost:4444/1234d -m 3
```
output:
``` bash
2025/02/28 11:52:33 [http2 request] Dump HTTP2 Frame error: connection error: COMPRESSION_ERROR
2025-02-28T11:52:33+08:00 ??? UUID:210635_210635_nghttp_5_1_[::1]:54222-[::1]:4444, Name:HTTP2Request, Type:2, Length:618
Frame Type	=>	SETTINGS
Frame StreamID	=>	0
Frame Type	=>	SETTINGS
Frame StreamID	=>	0
Frame Type	=>	PRIORITY
Frame StreamID	=>	3
Frame Type	=>	PRIORITY
Frame StreamID	=>	5
Frame Type	=>	PRIORITY
Frame StreamID	=>	7
Frame Type	=>	PRIORITY
Frame StreamID	=>	9
Frame Type	=> …
```
=> improve: handle COMPRESSION_ERROR to reduce the error log displayed

.github/workflows/go-c-cpp.yml, builder/init_env.sh
=> fix: #757 , update clang version to 10 in installation scripts

.github/workflows/go-c-cpp.yml, user/module/probe_gnutls_pcap.go, user/module/probe_gotls_pcap.go, user/module/probe_openssl_pcap.go
This pull request includes changes to the `setupManagersPcap` functions across multiple probe implementations to remove special handling for loopback devices. The most important changes include the removal of checks and comments related to loopback interfaces and the deletion of customized TC filter comments.
Removal of loopback device handling:
* [`user/module/probe_gnutls_pcap.go`](diffhunk://#diff-4fec8f06255579ed0d3c0f516162bb51bc0a34075500b6fec03eb56388894736L39-L44): Removed loopback device checks and related comments from `setupManagersPcap` function. [[1]](diffhunk://#diff-4fec8f06255579ed0d3c0f516162bb51bc0a34075500b6fec03eb56388894736L39-L44) [[2]](diffhunk://#diff-4fec8f06255579ed0d3c0f516162bb51bc0a34075500b6fec03eb56388894736L70-L78)
* …
=> refactor: remove loopback device checks from pcap probe files

pkg/event_processor/iworker.go
=> opt: redesign the truncate effect logic to reduce memory cost in text mode #718

pkg/event_processor/base_event.go, user/event/event_gnutls.go, user/event/event_nspr.go, user/event/event_openssl.go, user/module/imodule.go, user/module/probe_openssl.go
This pull request refactors and simplifies the `SSLDataEvent` handling in the `user/event/event_openssl.go` and `user/module/probe_openssl.go` files. The changes focus on improving code readability, modularizing functionality, and removing unused or commented-out code.
* Extracted common information formatting logic into a new method `BaseInfo` in the `SSLDataEvent` struct, reducing duplication across `StringHex` and `String` methods. (`[user/event/event_openssl.goL145-R189](diffhunk://#diff-480dff63c9fb64faab905b5e03148ce0c39eaf4ddfbf6fcda10d3d565642f83aL145-R189)`)
* Removed commented-out and unused code in the `StringHex`, `String`, and `dumpSslData` methods, as well as outdated comments in the `connDataEvent` struct. (`[[1]](diffhunk://#diff-480dff63c9fb64faab905b5e03148ce0c39eaf4ddfbf …
=> fix: clean up SSLDataEvent string methods and improve logging  #776

user/module/probe_pcap.go
fix #784
Key change:
* [`user/module/probe_pcap.go`](diffhunk://#diff-843cfd1b21b56be558d838830b906f9c699dd712b18d1b8f439a70a7466a894dR152-R157): Added a conditional check to ensure the `masterKeyBuffer` is not empty before attempting to write the decryption secrets block, resolving issue #542.
=> fix: avoid writing empty decryption secrets block in savePcapng method

kern/gotls_kern.c
由于使用 `bpf_probe_read_user_str` 方法读取 gotls client random 和 secret 导致若随机密钥中存在 `\x00` 字节，其后的内容会被忽略。因此改为使用 `bpf_probe_read_user` 方法。
以下是一个例子：
执行命令：
```bash
sudo ecapture gotls -m key -k keylog.log -e path/to/goelf
```
v1.3.1 输出结果: （其中有部分 client random 或 secret 带有大量 `00` 后缀）
```
CLIENT_RANDOM af8ca9934b499b382363e7252ec5405ed7d850e81d5e803fbcfd5df87f83eb8f a47f925e343a62dc293cca384d688c577fd29b0477a890e9bd3796bc0b5f8ae60f2b593dff90e9e66b7baaa58a15c5f4
CLIENT_RANDOM 84fde0396cdd8db9c9b7d209851b748e7129824c9e7984fc153e040f4e970aad 90c5cbfc1c69ad31b68706af7cd1e2c3a311f52162cbcbc9b2f8c2e20d5ffe0b92656fb10520d3e88092271f0acb8212
CLIENT_RANDOM b21a82cc2da65a34f44fb525a0c15bd13e8f5741fb08816736a345dd3cfd4f86 d030f9c8f6a5f8988782eebb1732c6b9b05c5e726ef67d33398b2ac78a7d99d95be88b19e6ee3ecf4a5d34e34924d1 …
```
=> fix: missing trailing bytes for some keys in gotls keylog

cli/cmd/ecaptureq.go, cli/cmd/root.go, pkg/ecaptureq/client.go, pkg/ecaptureq/hub.go, pkg/ecaptureq/proto.go, pkg/ecaptureq/server.go, pkg/event_processor/iworker.go, pkg/util/ws/server.go, pkg/util/ws/server_test.go, user/config/iconfig.go, user/event/event_base.go, user/event/event_gotls.go, user/event/ievent.go
support eCaptureQ
This pull request introduces several new features and refactors to the `ecaptureq` package, focusing on implementing a WebSocket server, creating a data model for packet handling, and improving the WebSocket utility. The changes add functionality for encoding and decoding packet data, handling WebSocket read/write operations, and managing concurrency through buffered channels.
* **Packet data model and JSON serialization**:
- Added the `PacketData` struct to represent packet information, including fields such as `Timestamp`, `SrcIP`, `DstIP`, and `PayloadBase64`. The struct uses JSON tags for serialization compatibility with frontend expectations.
- Implemented `Encode` and `Decode` methods for converting `PacketData` instances to and from JSON byte streams.
* …
=> feat: add WebSocket server and PacketData structure for log handling

.github/workflows/pr_build_debug.yml
This pull request refactors the debug build workflow in `.github/workflows/pr_build_debug.yml` to simplify the build matrix, streamline artifact naming, and improve the clarity and maintainability of the process. The changes also separate the job responsible for commenting on the PR with download links.
**Build matrix and artifact handling:**
* Simplified the build matrix by replacing the explicit list of artifact filenames with separate `os` and `arch` axes, making it easier to add or modify build targets in the future.
* Updated artifact naming and upload logic to dynamically generate artifact names based on the current matrix values, improving consistency and reducing duplication.
* Removed `.deb` package handling from the debug build process, focusing only on `.tar.gz` artifacts for …
=> fix: update GitHub Actions workflow for PR debug builds and artifact uploads

user/module/probe_openssl.go, user/module/probe_openssl_lib.go
This pull request refactors and enhances the OpenSSL probe's logic for selecting the appropriate BPF bytecode file when the exact OpenSSL/BoringSSL version is not found. The changes improve the robustness of version matching by introducing a downgrade mechanism and clarifying logging. The most important changes are:
* Added a new `downgradeOpensslVersion` method to attempt to find the closest lower matching version when the exact version is not available, improving compatibility with unknown or newer OpenSSL versions. (`user/module/probe_openssl_lib.go`)
* Replaced the previous default bytecode selection with a new `autoDetectBytecode` method that incorporates the downgrade logic and provides more informative logging when downgrading or defaulting. (`user/module/probe_openssl_lib.go`) …
=> feat: implement OpenSSL version downgrade logic and improve logging

user/module/probe_openssl_lib.go, utils/openssl_offset_3.0.sh, utils/openssl_offset_3.2.sh, utils/openssl_offset_3.3.sh, utils/openssl_offset_3.4.sh, utils/openssl_offset_3.5.sh
This pull request updates the version mapping and support for various OpenSSL 3.x releases across both the Go module and related shell scripts. The main goal is to add support for newer OpenSSL patch versions and ensure all version mappings are up to date and consistent.
**OpenSSL version support and mapping updates:**
* Updated version constants in `probe_openssl_lib.go` to support newer OpenSSL 3.0, 3.2, 3.3, 3.4, and 3.5 patch versions, including incrementing `MaxSupportedOpenSSL30Version` to 17, `SupportedOpenSSL32Version4` to 5, `MaxSupportedOpenSSL33Version` to 4, and others. (`user/module/probe_openssl_lib.go`)
* Updated the `sslVersionBpfMap` in `initOpensslOffset()` to correctly reference the latest supported OpenSSL patch versions, such as mapping 3.2.5 and 3.3.4 to their …
=> feat: update OpenSSL version offsets for 3.0, 3.2, 3.3, 3.4, and 3.5

.github/workflows/pr_build_debug.yml
> RequestError [HttpError]: Resource not accessible by integration
Error: Unhandled error: HttpError: Resource not accessible by integration
This pull request updates the GitHub Actions workflow for pull request debug builds. The main changes are the addition of explicit permissions for the workflow and an improved debug build completion message that includes the PR number and run ID.
Workflow configuration improvements:
* Added explicit permissions for `contents`, `issues`, and `pull-requests` with `write` access in `.github/workflows/pr_build_debug.yml` to ensure the workflow can perform required actions.
Debug build notification enhancements:
* Updated the debug build completion message in `.github/workflows/pr_build_debug.yml` to include the PR number and run ID for clearer …
=> feat: enhance PR build debug workflow with permissions and detailed completion message
