cli/cmd/root.go

cli: fix rootCmd.Long text typo

---

user/common.go
user/config_openssl.go

Fix #37 
cant find shared object file path while dependence an other shared object.

Fix #37 Shared object dependence

---

cli/cmd/bash.go
kern/bash_kern.c
kern/common.h
user/config_bash.go
user/const.go
user/probe_bash.go

add errnumber flag for command bash

---

.github/workflows/codeql-analysis.yml
.github/workflows/go-c-cpp.yml
.github/workflows/release.yml
go.mod
go.sum

New feature: update ebpfmanager package to 0.3.0

---

Makefile
main.go
pkg/util/ebpf/bpf.go
pkg/util/ebpf/bpf_android12.go
pkg/util/ebpf/bpf_linux.go
user/common.go
user/common_android12.go
user/common_linux.go

New feature: #87 support Android 12+

---

.github/workflows/go-c-cpp.yml

fixed: #92 github checkout error while a PR sent.

---

.github/workflows/codeql-analysis.yml
.github/workflows/go-c-cpp.yml
.github/workflows/release.yml
Makefile
builder/Makefile.release

New Feature: #79 Auto release for android gki

---

builder/Makefile.release

build: change tar.gz file path in checksum.txt

---

kern/bash_kern.c
kern/openssl_kern.c

fixed #108: ip address lost on aarch64 kernel 4.18

---

cli/cmd/bash.go
cli/cmd/tls.go
pkg/event_processor/iworker.go
pkg/event_processor/processor.go
user/imodule.go
user/probe_bash.go
user/probe_gnutls.go
user/probe_mysqld.go
user/probe_nspr.go
user/probe_openssl.go

document: message friendly

---

user/common.go
user/config_gnutls_linux.go
user/config_mysqld.go
user/config_nspr_linux.go
user/config_postgres.go
user/probe_bash.go
user/probe_gnutls.go
user/probe_mysqld.go
user/probe_nspr.go
user/probe_openssl.go
user/probe_postgres.go

fix #122  Clean up unnecessary information
```go
/apex/com.android.conscrypt/lib64/libnspr4.so: no such file or directory
tls module couldn't find binPath.
ecapture/user.(*MNsprProbe).start
/source_code/user/probe_nspr.go:53
```

user : Clean up unnecessary information.  fix #122

---

.github/workflows/codeql-analysis.yml

fixed #138 : You have an error in your yaml syntax on line 79

fixed #138 : You have an error in your yaml syntax on line 79

---

user/event_gossl.go
user/imodule.go

fix #147 
Co-Authored-By: chenhengqi <hengqi.chen@gmail.com>

user : echo String() or StringHex() by CLI argument.

---

.github/workflows/release.yml

workflows : build nocore version for Android default.

---

user/config_openssl_androidgki.go
user/config_openssl_linux.go

pkg : Ifname default value.

---

pkg/util/ebpf/bpf_linux.go
user/config_bash.go
user/probe_openssl.go
user/probe_openssl_tc.go

user : skip loopback network interface

---

pkg/util/ebpf/bpf_androidgki.go
pkg/util/ebpf/bpf_linux.go

pkg : fix config file parse failed, when as gzip format.

---

pkg/util/ebpf/bpf_androidgki.go
pkg/util/ebpf/bpf_linux.go

seek to file begin, after read 2 bit for check gzip magic.

fix gzip read err

---

user/probe_openssl_tc.go

user : fix incorrect TimeStamp

---

cli/cmd/bash.go
cli/cmd/mysqld.go
cli/cmd/postgres.go
cli/cmd/tls.go
user/imodule.go

cli/cmd : print version info

---

pkg/event_processor/iparser.go

pkg/event_processor: DefaultParser init().

---

pkg/util/hkdf/hkdf.go
pkg/util/hkdf/hkdf_test.go
user/module/probe_openssl.go

fix: use cipher id to derive secret

---

Makefile
cli/cmd/tls.go
user/module/imodule.go
user/module/probe_bash.go
user/module/probe_gnutls.go
user/module/probe_gossl.go
user/module/probe_mysqld.go
user/module/probe_nspr.go
user/module/probe_openssl.go
user/module/probe_postgres.go

user/module : compatiable  Linux kernel less or more than 5.2

---

utils/boringssl-offset.c

feat: unify boringssl-offset.c

---

cli/cmd/tls.go
user/module/probe_openssl.go
user/module/probe_openssl_lib.go
user/module/probe_openssl_tc.go

user/module: set --ssl_version flag ToLower().

---

user/module/probe_openssl_lib.go

user : Tolower openssl version strings.

---

cli/cmd/tls.go
user/module/probe_openssl_lib.go

cli : remove other modules on android.

---

utils/ecapture.lua

WIP :   utils: add eCapture lua script for wireshark plugin.

---

Makefile
README.md
README_CN.md
kern/ecapture.h

fix: Build failed on clang10 (#256)

---

builder/gen_android_nocore.sh

builder: rename android non-core archive file name

---

.github/workflows/codeql-analysis.yml
.github/workflows/go-c-cpp.yml
Makefile

makefile : support make parallel （#265）

---

cli/cmd/tls.go
user/config/common_androidgki.go
user/config/common_linux.go

disable gnutls/nss modules on Android.

---

README.md
README_CN.md
main.go
user/module/probe_openssl_lib.go

docs : update minimal kernel version as 4.18 (#274)

---

builder/init_env.sh

builder: fix typos (#285)

---

user/module/probe_gossl.go

fix(gossl): invalid memory address or nil pointer

---

user/event/event_gossl.go

user: fixes slice bounds out of range bug (#297)

---

kern/common.h
user/module/probe_bash.go

kern: fixes constant value of type uint64. (#301)

---

user/module/probe_postgres.go

Signed-off-by: spacewander <spacewanderlzx@gmail.com>

fix: typo in the section name

---

README_CN.md
README_JA.md
user/event/event_gotls.go

fixes:#322
Gotls crash : incorrect variable used.

Gotls crash : incorrect variable used. (fixes:#322) 

---

user/module/probe_tc.go

user: fixes the network card ID cannot be found when writing to a pcapng file. (#347)

---

user/module/probe_openssl_lib.go
utils/openssl_offset_1.1.1.sh
utils/openssl_offset_3.0.sh

support openssl new version
* 1.1.1u
* 3.0.8
* 3.0.9

feat:add openssl 1.1.1u and 3.0.9

---

user/config/config_openssl_linux.go
user/config/const.go

refactor : Shared Object (so) path load logic

---

LICENSE
user/event/event_gotls.go
user/module/probe_openssl.go

user : Set the connect hook as an optional parameter.

---

user/config/config_openssl_linux.go
user/module/probe_openssl.go

ignore connect symbol cant found.

---

user/module/probe_openssl_lib.go

Add optimization in openssl detection logic to consume less memory

---

user/module/probe_openssl_lib.go

user: return error when detect openssl version failed.

---

kern/boringssl_const.h
kern/common.h
kern/ecapture.h
user/module/const.go
user/module/probe_gotls.go
user/module/probe_openssl.go
user/module/probe_openssl_lib.go
user/module/probe_pcap.go

user : fixed the invalid address reference of the SSL_in_before symbol OpenSSL 1.0.2k.

---

README.md
README_CN.md
README_JA.md

Improve readability and internationalization.

readme: improve English README.md translation and add TOCs

---

user/module/imodule.go

BPF name should be appended after _core/_noncore

---

cli/cmd/root.go

fix #564 , used incorrect variable.

fix create output.log failed.

---

pkg/event_processor/processor.go
user/module/imodule.go

pkg: fix send on closed channel

---

kern/tc.h
user/module/probe_openssl_pcap.go

remove tcp packet limitation, allow capture udp/quic packet.

feat: remove tcp packet limitation

---

README_JA.md

docs: fix jp translation

---

cli/cmd/nspr.go
cli/cmd/root.go
user/module/probe_nspr.go

Change NSS-related naming to NSPR.

Add a reminder for failure when hooking libnss3.so.

---

.github/workflows/codeql-analysis.yml
.github/workflows/go-c-cpp.yml
.github/workflows/release.yml
builder/Dockerfile
builder/init_env.sh

see [GHSA-xmh6-39mf-3gh7](https://github.com/gojue/ecapture/security/advisories/GHSA-xmh6-39mf-3gh7) for more detail.

fix ecapture docker images CVE-2024-24790

---

pkg/event_processor/http2_request.go
pkg/event_processor/http2_response.go

improve: include a stream id field when parse http2 event

---

user/module/probe_openssl.go

fix: #739 ,  When the destroyed `event.ConnDataEvent` event is received, after a delay of 1 second, the quintile information is cleaned up.

fix: #739  the tuple to be unreachable.

---

pkg/event_processor/http2_request.go
pkg/event_processor/http2_response.go

improve: add frame length

---

user/module/probe_openssl.go

The delay in ebpf events processing in user mode may cause tuple not found, new AddConn with same pid will overwrite the tuple which will be deleted by DestroyConn. Add sock consistency check before tuple cleaning.

fix: #739 Add sock consistency check to void tuple miss.

---

README.md
README_CN.md
README_JA.md

We thank JetBrains for their contributions to the open-source community.

feat: add JetBrains logo and acknowledgements to README files

---

kern/gnutls_3_6_12_kern.c
kern/gnutls_3_6_13_kern.c
kern/gnutls_3_7_0_kern.c
kern/gnutls_3_7_3_kern.c
kern/gnutls_3_7_7_kern.c
kern/gnutls_3_8_4_kern.c
kern/gnutls_3_8_7_kern.c
kern/gnutls_masterkey.h
user/event/event_mastersecret_gnutls.go
user/module/probe_gnutls_keylog.go
user/module/probe_gnutls_lib.go
utils/gnutls_offset.c
utils/gnutls_offset.sh
variables.mk

feat: support gnutls early secret

feat: support gnutls early secret

---

user/config/config_bash.go
user/module/probe_bash.go

This commit addresses two issues in the bash probe logic:
1.  **Unreliable Bash Path Discovery:** The probe previously relied solely on the `$SHELL` environment variable. This could fail on systems where `$SHELL` is not set to bash (e.g., using zsh or fish) or is not set at all.
2.  **Incorrect Probe Attachment:** When bash was dynamically linked with `libreadline.so`, the probe incorrectly used the path to `libreadline.so` for all function hooks. This failed for functions like `execute_command`, `exec_builtin`, and `exit_builtin` which exist only in the main bash executable, not in the readline library.
This patch introduces the following fixes:
-   Adds a fallback to check for `/bin/bash` if a valid bash path cannot be determined from the `$SHELL` variable.
-   Refactors the …

fix: Improve bash path detection and correct probe attachment

---

kern/gotls_kern.c

Refer: https://github.com/gojue/ecapture/issues/838

kern/gotls_kern: refactored event creation logic
